### ISSUE TITLE
Error: Type "Mutation" was defined more than once.

### ISSUE THREAD

**Issue by mblode** [leveluptuts/fullstack-graphql-apollo-react-meteor#3]
I'm trying to expand on the API structure by creating a folder for a list type. But when I create a new type Mutation and import it into register-api, I get this: _"Error: Type 'Mutation' was defined more than once."_ How would you fix this?﻿

**Comment by stolinski** [comment]
Yeah! This threw me too when I was starting. You'll want to use the "extend" keyword for types that are defined in more than one file. Aka

```

extend type Mutation {
  createProduct(product: ProductInput!): Product
}
```

**Comment by stolinski** [comment]
Same goes for multiple Query defs.

**Comment by samhinshaw** [comment]
I was getting a similar error, and fixed it with `merge()`, as Scott mentioned in the YouTube comments: 
```js
const typeDefs = merge([QuerySchema, EntrySchema, UserSchema]);
```

**Comment by lilrose-dev** [comment]
I cannot realize the exact error. But i have this error "Type "Mutation" was defined more than once."
